services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Pemetaan port bisa disesuaikan sesuai kebutuhan
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
